-- MySQL Script generated by MySQL Workbench
-- Tue Feb  1 21:31:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

START TRANSACTION;

DROP TABLE IF EXISTS PERSONA_PARTICIPA_CAPITULO;
DROP TABLE IF EXISTS CLIENTE_COMENTA_SERIE;
DROP TABLE IF EXISTS CLIENTE_VALORA_CAPITULO;
DROP TABLE IF EXISTS CLIENTE CASCADE;
DROP TABLE IF EXISTS ADMINISTRADOR;
DROP TABLE IF EXISTS CAPITULO;
DROP TABLE IF EXISTS TEMPORADA;
DROP TABLE IF EXISTS SERIE_PERTENECE_GENERO;
DROP TABLE IF EXISTS SERIE;
DROP TABLE IF EXISTS GENERO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS PERSONA;

-- -----------------------------------------------------
-- Table SERIE
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS SERIE (
  titulo VARCHAR(45) NOT NULL,
  fecha_estreno DATE NULL,
  idioma VARCHAR(15) NOT NULL,
  sinopsis VARCHAR(400) NULL,
  PRIMARY KEY (titulo));

-- -----------------------------------------------------
-- Table GENERO
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS GENERO (
  nombre VARCHAR(20) NOT NULL,
  descripcion VARCHAR(400) NULL,
  PRIMARY KEY (nombre));

-- -----------------------------------------------------
-- Table TEMPORADA
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS TEMPORADA (
  numero_temporada INT NOT NULL,
  titulo_serie VARCHAR(45) NOT NULL,
  cantidad_capitulos INT NOT NULL,
  fecha_estreno DATE NULL,
  PRIMARY KEY (numero_temporada, titulo_serie),
  CONSTRAINT fk_TEMPORADA_SERIE1
    FOREIGN KEY (titulo_serie)
    REFERENCES SERIE (titulo)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table CAPITULO
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS CAPITULO (
  numero_capitulo INT NOT NULL,
  titulo_serie VARCHAR(45) NOT NULL,
  numero_temporada INT NOT NULL,
  titulo VARCHAR(45) NOT NULL,
  duracion INT NULL,
  fecha_estreno DATE NULL,
  valoracion FLOAT NULL DEFAULT 0,
  PRIMARY KEY (numero_capitulo, titulo_serie, numero_temporada),
  CONSTRAINT fk_CAPITULO_TEMPORADA1
    FOREIGN KEY (numero_temporada , titulo_serie)
    REFERENCES TEMPORADA (numero_temporada , titulo_serie)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table USUARIO
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS USUARIO (
  email VARCHAR(100) NOT NULL,
  nombre VARCHAR(45) NOT NULL,
  apellido1 VARCHAR(45) NOT NULL,
  apellido2 VARCHAR(45) NULL,
  PRIMARY KEY (email));

-- -----------------------------------------------------
-- Table PERSONA
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS PERSONA (
  nombre_artistico VARCHAR(50) NOT NULL,
  nombre VARCHAR(45) NOT NULL,
  apellido1 VARCHAR(45) NOT NULL,
  apellido2 VARCHAR(45) NULL,
  nacionalidad VARCHAR(15) NULL,
  fecha_nacimiento DATE NULL,
  PRIMARY KEY (nombre_artistico));

-- -----------------------------------------------------
-- Table SERIE_PERTENECE_GENERO
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS SERIE_PERTENECE_GENERO (
  titulo_serie VARCHAR(45) NOT NULL,
  nombre_genero VARCHAR(20) NOT NULL,
  PRIMARY KEY (titulo_serie, nombre_genero),
  CONSTRAINT fk_SERIE_PERTENECE_GENERO_GENERO1
    FOREIGN KEY (nombre_genero)
    REFERENCES GENERO (nombre)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_SERIE_PERTENECE_GENERO_SERIE1
    FOREIGN KEY (titulo_serie)
    REFERENCES SERIE (titulo)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table PERSONA_PARTICIPA_CAPITULO
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS PERSONA_PARTICIPA_CAPITULO (
  rol VARCHAR(45) NOT NULL,
  nombre_artistico VARCHAR(50) NOT NULL,
  titulo_serie VARCHAR(45) NOT NULL,
  numero_temporada INT NOT NULL,
  numero_capitulo INT NOT NULL,
  PRIMARY KEY (rol, nombre_artistico, titulo_serie, numero_temporada, numero_capitulo),
  CONSTRAINT fk_PERSONA_PARTICIPA_CAPITULO_PERSONA1
    FOREIGN KEY (nombre_artistico)
    REFERENCES PERSONA (nombre_artistico)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_PERSONA_PARTICIPA_CAPITULO_CAPITULO1
    FOREIGN KEY (numero_temporada, titulo_serie, numero_capitulo)
    REFERENCES CAPITULO (numero_temporada , titulo_serie , numero_capitulo)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table ADMINISTRADOR
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS ADMINISTRADOR (
  sueldo FLOAT CHECK (sueldo >= 1050.00) NOT NULL,
  email_administrador VARCHAR(100) NOT NULL,
  PRIMARY KEY (email_administrador),
  CONSTRAINT fk_ADMINISTRADOR_USUARIO1
    FOREIGN KEY (email_administrador)
    REFERENCES USUARIO (email)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table CLIENTE
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS CLIENTE (
  suscripcion VARCHAR(45) CHECK (suscripcion = 'Mensual' OR suscripcion = 'Anual') NOT NULL,
  email_cliente VARCHAR(100) NOT NULL,
  PRIMARY KEY (email_cliente),
  CONSTRAINT fk_CLIENTE_USUARIO1
    FOREIGN KEY (email_cliente)
    REFERENCES USUARIO (email)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table CLIENTE_COMENTA_SERIE
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS CLIENTE_COMENTA_SERIE (
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  titulo_serie VARCHAR(45) NOT NULL,
  email_cliente VARCHAR(100) NOT NULL,
  comentario VARCHAR(400) NOT NULL,
  PRIMARY KEY (fecha, titulo_serie, email_cliente),
  CONSTRAINT fk_CLIENTE_COMENTA_SERIE_CLIENTE1
    FOREIGN KEY (email_cliente)
    REFERENCES CLIENTE (email_cliente)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_CLIENTE_COMENTA_SERIE_SERIE1
    FOREIGN KEY (titulo_serie)
    REFERENCES SERIE (titulo)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table CLIENTE_VALORA_CAPITULO
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS CLIENTE_VALORA_CAPITULO (
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email_cliente VARCHAR(100) NOT NULL,
  titulo_serie VARCHAR(45) NOT NULL,
  numero_temporada INT NOT NULL,
  numero_capitulo INT NOT NULL,
  puntuacion FLOAT CHECK (puntuacion >= 1 AND puntuacion <= 10) NOT NULL,
  PRIMARY KEY (email_cliente, titulo_serie, numero_temporada, numero_capitulo),
  CONSTRAINT fk_CLIENTE_VALORA_CAPITULO_CLIENTE1
    FOREIGN KEY (email_cliente)
    REFERENCES CLIENTE (email_cliente)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_CLIENTE_VALORA_CAPITULO_CAPITULO1
    FOREIGN KEY (numero_capitulo , titulo_serie , numero_temporada)
    REFERENCES CAPITULO (numero_capitulo , titulo_serie , numero_temporada)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
  
COMMIT;